### ISSUE TITLE
Look forward to other 9 multi-modal dataset like US_FLURATIO_Week.csv in Time-MMD

### ISSUE THREAD

**Issue by dongjiaxiang** [AdityaLab/MM-TSFlib#1]
Hello, thank you for your constructive and valuable work. I have a question about the multi-modal dataset Time-MMD that you proposed in your paper. It contains datasets from 10 domains, but only one multi-modal example, US_FLURATIO_Week.csv, is provided in MM-TSFlib. I noticed that the data structure in Time-MMD, Health_US is based on a combination of numerical and textual information. I'm wondering if it's possible to provide data for the other nine domains in a similar format to US_FLURATIO_Week.csv, or if you could provide a script for synthesizing multi-modal data based on numerical and textual information in Time-MMD. This would greatly facilitate the use of this dataset. Hoping for your feedback!

**Comment by dongjiaxiang** [comment]
And when we execute the script week_health.sh, we find that the US_FLURATIO_Week.csv contains several other variables besides the target variable OT, but some of them are character variables and cannot be processed properly. When we set --features = M or MS, an exception occurs. For the entire Time-MMD dataset, which includes US_FLURATIO_Week.csv, can you provide the variables that are relevant for the OT dataset? Or the dataset is only available in the univariate case? Hopefully, the author can provide the script that works.
![mmddt](https://github.com/user-attachments/assets/6ccd4d0b-7117-4ed6-b015-b52cb0378df1)

**Comment by haoxin1998** [comment]
We currently only support single variable. We will upload all pre-processed data. At this three datasets are uploaded.
